version: '3.0'

services:

  customer-frontend:
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

    # don't forget to add this or else docker-compose will not work 
    # https://github.com/facebook/create-react-app/issues/8688#issuecomment-602110747
    stdin_open: true